# Generated by Django 3.2.25 on 2024-05-23 19:15

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS review_review_recommend;",
        ),
    ]