# Generated by Django 3.2.25 on 2024-06-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age_group',
            field=models.CharField(choices=[('adult', 'Adult'), ('child', 'Child')], default='adult', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_certification',
            field=models.BooleanField(default=False),
        ),
    ]
